### PR TITLE
Jesse

### PR DESCRIPTION
**Pull request by jecastan**
Adjusts the columns on the volunteer overview page to fit cleanly on a standard aspect ratio single window.
Adds a modal view based on the one incorporated to edit the client details.
I still need to add a number of fields to the modal edit details window, but I think I got the baseline functionality down.
I think it's worth it to submit a pull request for the current state to make sure I didn't mess anything else up and I'll submit another one once I finalize what columns to include in the overview and what fields are necessary in the edit details window.

### CODE REVIEW

**Review by EmilyGavrilenko — CHANGES_REQUESTED** [review]
Looks much better, but I tried editing the volunteer details directly from the overview page and the data wasn't saved when I refreshed the page. Do you think you could fix the updateDatabase function in the VolunteerOverviewTable file (line 75). Thanks!

**Comment by jecastan** [comment]
Oops, thanks for catching that Emily. I'll take a look and get it resolved!

**Comment by jecastan** [comment]
Emily,
I finally figured out how to adjust the database from the volunteer table view.
The cellProperties were really throwing me for a loop for awhile!
But checking the conflicts that exist, it looks like you guys have already resolved this issue?
Do you still want to use any of this pull request? Or should I erase my local changes and re-merge with master?
-Jesse

**Comment by EmilyGavrilenko** [comment]
I should have communicated with you about the update database function, I was just working on it this morning! I'll keep your changes since you worked so hard on them, especially since the table is updated with the columns you want.

**Comment by jecastan** [comment]
Aww thanks Emily, I'm certainly learning a lot!

**Pull request merged**
